services:
  gotty:
    image: dannyben/gotty-ruby
    ports: ["3000:3000"]
    <<: &default
      build: .
      volumes:
      - "./app:/app"
      - "./files/home:/root"

  bash:
    <<: *default
    entrypoint: bash

